### ISSUE TITLE
Can't install [1.1] 'Project Orion' Nuclear Pulse Engine using CKAN. Error USI Core missing

### ISSUE THREAD

**Issue by nobodyhasthis** [BobPalmer/NuclearRockets#12]
Can't install [1.1] 'Project Orion' Nuclear Pulse Engine using CKAN without getting a popup 

Error: Module USI-Core has not been found. This may be because it is not compatible with the currently installed version of KSP

Last tested on CKAN 1.16.1 for KSP version

build id = 01174
2016.03.31 at 00:58:13 CEST
Branch: prerelease

Readme.txt Version 1.1.0 Pre-release

**Comment by BobPalmer** [comment]
The current versions of these mods are all for KSP 1.1, not KSP 1.0.5 - I've confirmed the KSP-AVC version files, so this is going to be a CKAN issue.

**Comment by nobodyhasthis** [comment]
Turns out it was the Firespitter dependency. New issue raised in CKAN to pull mods that are not available when dependency fails after one layer.
