### ISSUE TITLE
unused (?) Nuke*.mu's

### ISSUE THREAD

**Issue by khr15714n** [BobPalmer/NuclearRockets#4]
UmbraSpaceIndustries/Orion/Assets/NukeFlash.mu
UmbraSpaceIndustries/Orion/Assets/NukeRadiation.mu
UmbraSpaceIndustries/Orion/Assets/NukeSparks.mu

Tiny mus using fire.dds and flash.dds which are also used by MedusaDrive.mu and OrionDrive.mu (the dds).
Am I not recognizing their usage or are they leftovers or wip for future feature?

**Comment by BobPalmer** [comment]
Those are particle effects
